language: php

services: mysql

env:
  - DB=mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

branches:
  only:
    - master

before_script:
  - composer install --no-dev
  - /etc/init.d/mysql start || 1
  - mysql -uroot < tests/fixtures/main.sql

script:
  - phpunit --coverage-text
