language: php

services: mysql

env:
  - DB=mysql

before_script:
  - composer install --no-dev --verbose
  - /etc/init.d/mysql start || 1
  - mysql -uroot < tests/fixtures/main.sql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
  - phpunit --coverage-text
